springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    root: warn
    ru.agimate: info

server:
  forward-headers-strategy: framework
  tomcat:
    mbeanregistry:
      enabled: false
