package ru.agimate.common.util;

import java.security.SecureRandom;
import java.time.Instant;
import java.util.UUID;
import java.util.zip.CRC32;

/**
 * Utility class for generating and validating UUIDs.
 * Provides methods for generating UUIDv8s with validation capabilities.
 */
public class UUIDUtils {
    private static final SecureRandom secureRandom = new SecureRandom();
    private static final String SECRET_KEY = "agimate"; // This should be configured externally in production

    /**
     * Generates a time-based UUID (UUIDv8) with embedded checksum for validation.
     * This approach provides both time-ordering and validation capabilities.
     * The checksum is calculated from the random parts of the UUID, ensuring uniqueness.
     * <p>
     * Bit structure:
     * - 0-47:  timestamp (48 bits)
     * - 48-51: version (4 bits, value 1000 for UUIDv8)
     * - 52-63: random1 (12 bits)
     * - 64-65: variant (2 bits, fixed value 10 for RFC 4122)
     * - 66-111: random2 (46 bits)
     * - 112-127: first 16 bits of CRC32(random1 + random2 + secret)
     *
     * @return A new UUIDv8 with embedded validation data
     */
    // Static counter to ensure ordering within same timestamp
    private static volatile long lastTimeMs = 0;
    private static volatile int sequence = 0;

    public static UUID generateUUIDv8() {
        long wallClockMilliTime = Instant.now().toEpochMilli() - 542280896789L;

        // Scale the wall-clock nanoTime to create a meaningful timestamp
        // We'll use the same scaling factor (314/100) and keep only the 48 most significant bits
        long scaledTime = wallClockMilliTime * 314 / 100;

        // Handle sequence within same scaled timestamp for proper ordering
        synchronized (UUIDUtils.class) {
            if (scaledTime <= lastTimeMs) {
                // If the same scaled timestamp occurs, increment to ensure ordering
                scaledTime = lastTimeMs + 1;
                sequence++;
            } else {
                lastTimeMs = scaledTime;
                sequence = 0;
            }
        }

        // Generate secure random bits using SecureRandom
        long random1 = (secureRandom.nextInt() & 0x00000FFFL); // 12 bits: positions 52-63
        long random2 = (secureRandom.nextLong() & 0x00003FFFFFFFFFFFL); // 46 bits: positions 66-111

        // Most significant bits (64 bits):
        // - 0-47:  timestamp (48 bits)
        // - 48-51: version (4 bits, value 8)
        // - 52-63: random1 (12 bits)
        long mostSigBits = ((scaledTime & 0xFFFFFFFFFFFFL) << 16) |      // 48 bits: timestamp (0-47)
                (8L << 12) |               // 4 bits: version (48-51)
                random1;                   // 12 bits: random1 (52-63)

        // Least significant bits (64 bits):
        // - 0-1:   variant (2 bits, value 10 for RFC 4122) - positions 64-65 in full UUID
        // - 2-47:  remaining part of random2 (46 bits) - positions 66-111 in full UUID
        // - 48-63: checksum (16 bits) - positions 112-127 in full UUID
        long leastSigBits = (2L << 62) |                                    // 2 bits: variant (64-65)
                ((random2 & 0x00003FFFFFFFFFFFL) << 16);          // 46 bits: random2 (66-111)

        // Calculate a checksum based on ALL bits from 0 to 111 (the entire UUID except the checksum)
        // and the secret key
        CRC32 crc = new CRC32();
        crc.update(longToBytes(mostSigBits));    // bits 0-63
        crc.update(longToBytes(leastSigBits));   // bits 64-127 (without the CRC part)
        crc.update(SECRET_KEY.getBytes());
        long checksum = crc.getValue() & 0x0000FFFFL; // Take only 16 bits: positions 112-127

        // Add the checksum to the least significant bits
        leastSigBits |= checksum;                // 16 bits: checksum (112-127)

        return new UUID(mostSigBits, leastSigBits);
    }

    /**
     * Validates if the UUID was generated by generateUUIDv8() method.
     * The validation recalculates the checksum from the random parts of the UUID.
     *
     * @param uuidString The UUID string to validate
     * @return true if the UUID is valid, false otherwise
     */
    public static boolean validateUUIDv8(String uuidString) {
        if (uuidString == null) {
            return false;
        }

        UUID uuid;
        try {
            uuid = UUID.fromString(uuidString);
        } catch (IllegalArgumentException e) {
            return false; // Invalid UUID format
        }

        // Only validate UUIDv8 - check version field in the most significant bits
        // Version is stored in bits 48-51 of the most significant bits
        long version = (uuid.getMostSignificantBits() >> 12) & 0xFL;
        if (version != 8) {
            return false;
        }

        // To validate, we need to calculate the checksum from the first 112 bits (0-111) of the UUID
        // and compare it with the last 16 bits (112-127) which is the stored checksum
        long originalMostSigBits = uuid.getMostSignificantBits();
        long originalLeastSigBits = uuid.getLeastSignificantBits();

        // Create a copy of the least significant bits with the checksum part zeroed out
        long leastSigBitsWithoutChecksum = originalLeastSigBits & 0xFFFFFFFFFFFF0000L;

        // Calculate expected checksum from ALL the first 112 bits (the entire UUID except checksum) and the secret key
        CRC32 crc = new CRC32();
        crc.update(longToBytes(originalMostSigBits));        // bits 0-63
        crc.update(longToBytes(leastSigBitsWithoutChecksum)); // bits 64-111 (without the checksum part)
        crc.update(SECRET_KEY.getBytes());
        long expectedChecksum = crc.getValue() & 0x0000FFFFL;

        // Extract checksum from the UUID (bits 112-127 of least significant bits)
        long actualChecksum = originalLeastSigBits & 0x000000000000FFFFL;

        return expectedChecksum == actualChecksum;
    }

    /**
     * Helper method to convert a long value to byte array
     */
    private static byte[] longToBytes(long value) {
        return new byte[]{
                (byte) (value >>> 56),
                (byte) (value >>> 48),
                (byte) (value >>> 40),
                (byte) (value >>> 32),
                (byte) (value >>> 24),
                (byte) (value >>> 16),
                (byte) (value >>> 8),
                (byte) value
        };
    }
}