GET http://api.agimate.lc:8000/connectors-api/call/mobile/devices
X-Api-Key: ***REMOVED***

### test connectors
GET http://api.agimate.lc:8000/connectors-api/api/connectors/
X-Api-Key: ***REMOVED***

### test credentials
GET http://api.agimate.lc:8000/connectors-api/api/credentials/mobile
X-Api-Key: ***REMOVED***



### test credentials
GET http://api.agimate.lc:8000/connectors-api/api/methods/ozon
X-Api-Key: ***REMOVED***

