syntax = "proto3";

package ru.agimate.connectors.v1;

option java_package = "ru.agimate.connectors.v1";
option java_multiple_files = true;
option java_outer_classname = "ConnectorsEventApiProto";

service ConnectorsEventService {
  rpc HandleEvent(HandleEventRequest) returns (HandleEventResponse);
}

message HandleEventRequest {
  string event_name = 1;
  string user_pub_id = 2;
  string credential_id = 3;
  string device_id = 4;
  string params_json = 5;
}

message HandleEventResponse {
  bool accepted = 1;
}
