package ru.agimate.controlapi.database.entities;

import jakarta.persistence.*;
import lombok.*;
import ru.agimate.common.persistence.BaseEntity;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * The single registry of connector instances. {@code id} is the {@code connectionId} across all
 * downstream tables (channels, policies, trigger_logs, tool_call_logs, connector_jobs). It subsumes
 * {@code integration_credentials}; {@code apps} is referenced through {@link #appId} (device and
 * auth data are not duplicated).
 *
 * <p>{@code full_code = connector_code + "_" + sub_code} — the stable client-facing handle and the
 * prefix of the tool namespace (mcp_context7.resolve-library-id); for a static singleton it equals
 * {@code connector_code}.
 *
 * <p>Uniqueness among active rows: {@code (connector_code, user_id, sub_code)} and
 * {@code (full_code, user_id)} — partial unique indexes {@code WHERE deleted_at IS NULL} (see the
 * migration {@code initial-24-connections.xml}). JPA {@code @UniqueConstraint} cannot express a
 * partial one, so it is not declared.
 */
@Entity
@Table(name = "connections")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Connection extends BaseEntity {

    /**
     * Assigned explicitly on creation ({@code UUIDUtils.generateUUIDv8()} for integrations,
     * {@code app.id} for APP, the old id when backfilling) — id is the {@code connectionId} across
     * all downstream tables, so it is not generated by the database.
     */
    @Id
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "connector_code", nullable = false, columnDefinition = "TEXT")
    private String connectorCode;

    @Column(name = "sub_code", columnDefinition = "TEXT")
    private String subCode;

    @Column(name = "full_code", nullable = false, columnDefinition = "TEXT")
    private String fullCode;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @Column(name = "name", columnDefinition = "TEXT")
    private String name;

    /** Outbound credentials (telegram/mcp): a reference into {@code secrets}. {@code null} for internal/app. */
    @Column(name = "secret_id")
    private UUID secretId;

    /** APP type: a reference into {@code apps} (device auth and linking are not duplicated). */
    @Column(name = "app_id")
    private UUID appId;

    /**
     * Secret used to validate incoming webhooks: a reference into {@code secrets}
     * (entity = {@code connection_webhook}, AAD owner = {@code id}). {@code null} when the connector
     * has no webhooks.
     */
    @Column(name = "webhook_secret_id")
    private UUID webhookSecretId;

    @Column(name = "enabled", nullable = false)
    @Builder.Default
    private Boolean enabled = true;

    @Column(name = "last_used_at")
    private LocalDateTime lastUsedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;

    public boolean isDeleted() {
        return deletedAt != null;
    }

    public boolean isActive() {
        return enabled && !isDeleted();
    }
}
