package ru.agimate.controlapi.database.entities;

import jakarta.persistence.*;
import lombok.*;
import ru.agimate.common.persistence.BaseEntity;
import ru.agimate.controlapi.database.enums.ConnectionAuthStatus;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * The single registry of connector instances. {@code id} is the {@code connectionId} across all
 * downstream tables (channels, policies, trigger_logs, tool_call_logs, connector_jobs). It subsumes
 * {@code integration_credentials}; {@code apps} is referenced through {@link #appId} (app auth and
 * device linking are not duplicated).
 *
 * <p>{@code full_code = connector_code + "_" + sub_code} — the stable client-facing handle and the
 * prefix of the tool namespace (mcp_context7.resolve-library-id); for a static singleton it equals
 * {@code connector_code}.
 *
 * <p>Uniqueness among active rows: {@code (connector_code, user_id, exclusive_sub_code)} and
 * {@code (full_code, user_id)} — partial unique indexes {@code WHERE deleted_at IS NULL}. JPA
 * {@code @UniqueConstraint} cannot express a partial one, so neither is declared here.
 */
@Entity
@Table(name = "connections")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Connection extends BaseEntity {

    /**
     * Assigned explicitly on creation ({@code UUIDUtils.generateUUIDv8()} for integrations,
     * {@code app.id} for APP, the old id when backfilling) — id is the {@code connectionId} across
     * all downstream tables, so it is not generated by the database.
     */
    @Id
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "connector_code", nullable = false, columnDefinition = "TEXT")
    private String connectorCode;

    @Column(name = "sub_code", columnDefinition = "TEXT")
    private String subCode;

    /**
     * Uniqueness key among the user's active rows of one connector: equals {@link #subCode} where a
     * second instance of the same account is harmful, {@code null} where multiple accounts are
     * legitimate (MCP). Filled from {@code IntegrationConnectorHandler.allowsMultipleInstances()};
     * NULLs never collide on the partial unique index.
     */
    @Column(name = "exclusive_sub_code", columnDefinition = "TEXT")
    private String exclusiveSubCode;

    @Column(name = "full_code", nullable = false, columnDefinition = "TEXT")
    private String fullCode;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @Column(name = "name", columnDefinition = "TEXT")
    private String name;

    /** Outbound credentials (telegram/mcp): a reference into {@code secrets}. {@code null} for internal/app. */
    @Column(name = "secret_id")
    private UUID secretId;

    /** APP type: a reference into {@code apps} (app auth and device linking are not duplicated). */
    @Column(name = "app_id")
    private UUID appId;

    /**
     * Secret used to validate incoming webhooks: a reference into {@code secrets}
     * (entity = {@code connection_webhook}, AAD owner = {@code id}). {@code null} when the connector
     * has no webhooks.
     */
    @Column(name = "webhook_secret_id")
    private UUID webhookSecretId;

    @Column(name = "enabled", nullable = false)
    @Builder.Default
    private Boolean enabled = true;

    /**
     * Authorisation state. Static-credential connections are born {@code AUTHORIZED}; an OAuth one is
     * born {@code PENDING_AUTH} and becomes usable only after the flow completes.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "auth_status", nullable = false, columnDefinition = "TEXT")
    @Builder.Default
    private ConnectionAuthStatus authStatus = ConnectionAuthStatus.AUTHORIZED;

    /** One-time OAuth {@code state}; lives only between {@code /authorize} and completion. */
    @Column(name = "oauth_state", columnDefinition = "TEXT")
    private String oauthState;

    @Column(name = "oauth_state_expires_at")
    private LocalDateTime oauthStateExpiresAt;

    /** Expiry of the access token; {@code null} means «unknown» (no {@code expires_in}), never «expired». */
    @Column(name = "oauth_expires_at")
    private LocalDateTime oauthExpiresAt;

    @Column(name = "last_used_at")
    private LocalDateTime lastUsedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;

    public boolean isDeleted() {
        return deletedAt != null;
    }

    /**
     * Exists and is switched on. Deliberately blind to {@link #authStatus}: the refresh job must run
     * exactly when the authorisation is broken, and {@code JobExecutionService} filters on this.
     */
    public boolean isActive() {
        return enabled && !isDeleted();
    }

    /**
     * Fit to serve traffic — active <em>and</em> authorised. Tool listing does not use this: the
     * cached tool set outlives the token, and an agent is better off with an explicit «re-authorise»
     * on the call than with half its tools silently gone.
     */
    public boolean isUsable() {
        return isActive() && authStatus == ConnectionAuthStatus.AUTHORIZED;
    }
}
