syntax = "proto3";

package ru.agimate.agentworker;

option java_multiple_files = true;
option java_package = "ru.agimate.agentworker";
option java_outer_classname = "WorkerControlProto";

import "google/protobuf/timestamp.proto";

service WorkerControl {
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse);
  rpc SendMessage(SendMessageRequest) returns (SendMessageResponse);
}

message HealthCheckRequest {}

message HealthCheckResponse {
  string status = 1;
  google.protobuf.Timestamp server_time = 2;
  string pool_id = 3;
}

enum WorkerMessageType {
  WORKER_MESSAGE_TYPE_UNSPECIFIED = 0;
  WORKER_MESSAGE_TYPE_MESSAGE = 1;
  WORKER_MESSAGE_TYPE_ERROR = 2;
}

message SendMessageRequest {
  WorkerMessageType type = 1;
  string content = 2;
}

message SendMessageResponse {}
