

### Check is this endpoint abailable
GET http://localhost:8080/user-api/user/me

### authrization throuth google
GET http://localhost:8080/user-api/oauth2/authorization/google


###
GET http://localhost:8080/user-api/user/me
Authorization: Bearer ***REMOVED***"


### 123
POST  http://localhost:8080/user-api/oauth2/refresh
Content-Type: application/json

{
    "refreshToken": "7ed25ce0-c4c3-43fa-b19e-5f0366b230e1"
}
