

### Check is this endpoint abailable
GET http://localhost:8080/user-api/user/me

### authrization throuth google
GET http://localhost:8080/user-api/oauth2/authorization/google


###
GET http://localhost:8080/user-api/user/me
Authorization: Bearer ***REMOVED***


### 123
GET http://localhost:8080/user-api/auth/refresh
Content-Type: application/json

{
    "refresh_token": "f315dedd-7958-4355-9e06-8c77de5bff27"
}
