POST http://localhost:8180/control-api/control/trigger/new
X-Device-Auth-Key: ***REMOVED***
Content-Type: application/json

{
  "name": "test",
  "data": {
    "lol": "val"
  }
}


###
POST http://localhost:9000/api/publish
Authorization: apikey ***REMOVED***
Content-Type: application/json

{
  "channel": "device:8dbacd6c-41b4-4e9e-a188-8392e912268f:actions",
  "data": {
    "type": "TTS",
    "parameters": {
      "text": "как дела? я тебя люблю!"
    }
  }
}

###
POST http://localhost:9000/api/publish
Authorization: apikey ***REMOVED***
Content-Type: application/json

{
  "channel": "device:8dbacd6c-41b4-4e9e-a188-8392e912268f:actions",
  "data": {
    "type": "NOTIFICATION",
    "parameters": {
      "title": "Alert",
      "message": "Something important happened"
    }
  }
}
