spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/am_connectors_db_test"
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    ru.agimate: debug
