package ru.agimate.common.util;

import java.security.SecureRandom;
import java.time.Instant;
import java.util.UUID;
import java.util.zip.CRC32;

/**
 * Utility class for generating and validating UUIDs.
 * Provides methods for generating UUIDv8s with validation capabilities.
 */
public class UUIDUtils {
    private static final SecureRandom secureRandom = new SecureRandom();
    private static final String SECRET_KEY = "agimate"; // This should be configured externally in production

    // Last emitted counter value; guards strict monotonicity when two calls land on the same tick.
    private static volatile long lastTimeMs = 0;
    private static volatile int sequence = 0;

    /**
     * Generates a time-based UUID (UUIDv8) with an embedded checksum, so that an identifier
     * can be rejected as not-ours before it ever reaches the database.
     * <p>
     * Bit structure, by position in the full 128-bit UUID:
     * <pre>
     *   0-47    counter    (48 bits, monotonic — see generateUUIDv8 body)
     *   48-51   version    (4 bits, value 8)
     *   52-63   random1    (12 bits)
     *   64-65   variant    (2 bits, value 10 for RFC 4122)
     *   66-111  random2    (46 bits)
     *   112-127 checksum   (16 bits)
     * </pre>
     * The checksum is the <b>low</b> 16 bits of {@code CRC32(bits 0-111 || SECRET_KEY)} — it covers
     * the entire UUID except itself, counter and version included, not only the random parts.
     * CRC32 with a fixed salt is a typo filter, not a signature: anyone holding the constant can
     * mint a passing id.
     *
     * @return A new UUIDv8 with embedded validation data
     */
    public static UUID generateUUIDv8() {
        // The offset and the 3.14 ticks/ms scale carry no meaning of their own: together they only
        // keep the counter monotonic and inside 48 bits. The field is not decodable back to
        // wall-clock time, and nothing in the codebase tries to.
        long wallClockMilliTime = Instant.now().toEpochMilli() - 542280896789L;
        long scaledTime = wallClockMilliTime * 314 / 100;

        synchronized (UUIDUtils.class) {
            if (scaledTime <= lastTimeMs) {
                scaledTime = lastTimeMs + 1;
                sequence++;
            } else {
                lastTimeMs = scaledTime;
                sequence = 0;
            }
        }

        long random1 = (secureRandom.nextInt() & 0x00000FFFL); // 12 bits: positions 52-63
        long random2 = (secureRandom.nextLong() & 0x00003FFFFFFFFFFFL); // 46 bits: positions 66-111

        long mostSigBits = ((scaledTime & 0xFFFFFFFFFFFFL) << 16) |      // 48 bits: counter (0-47)
                (8L << 12) |               // 4 bits: version (48-51)
                random1;                   // 12 bits: random1 (52-63)

        long leastSigBits = (2L << 62) |                                    // 2 bits: variant (64-65)
                ((random2 & 0x00003FFFFFFFFFFFL) << 16);          // 46 bits: random2 (66-111)

        // Checksum bits are still zero here, so this hashes exactly bits 0-111.
        CRC32 crc = new CRC32();
        crc.update(longToBytes(mostSigBits));    // bits 0-63
        crc.update(longToBytes(leastSigBits));   // bits 64-127 (without the CRC part)
        crc.update(SECRET_KEY.getBytes());
        long checksum = crc.getValue() & 0x0000FFFFL; // low 16 bits → positions 112-127

        leastSigBits |= checksum;

        return new UUID(mostSigBits, leastSigBits);
    }

    /**
     * Validates if the UUID was generated by generateUUIDv8() method.
     * Recomputes the checksum over bits 0-111 with the checksum field zeroed out, and compares
     * it with the stored one. A pass means «well-formed and salted with our constant», nothing more.
     *
     * @param uuidString The UUID string to validate
     * @return true if the UUID is valid, false otherwise
     */
    public static boolean validateUUIDv8(String uuidString) {
        if (uuidString == null) {
            return false;
        }

        UUID uuid;
        try {
            uuid = UUID.fromString(uuidString);
        } catch (IllegalArgumentException e) {
            return false; // Invalid UUID format
        }

        long version = (uuid.getMostSignificantBits() >> 12) & 0xFL; // positions 48-51
        if (version != 8) {
            return false;
        }

        long originalMostSigBits = uuid.getMostSignificantBits();
        long originalLeastSigBits = uuid.getLeastSignificantBits();

        // Zeroing the checksum field reproduces the exact input the generator hashed.
        long leastSigBitsWithoutChecksum = originalLeastSigBits & 0xFFFFFFFFFFFF0000L;

        CRC32 crc = new CRC32();
        crc.update(longToBytes(originalMostSigBits));         // bits 0-63
        crc.update(longToBytes(leastSigBitsWithoutChecksum)); // bits 64-111
        crc.update(SECRET_KEY.getBytes());
        long expectedChecksum = crc.getValue() & 0x0000FFFFL;

        long actualChecksum = originalLeastSigBits & 0x000000000000FFFFL; // positions 112-127

        return expectedChecksum == actualChecksum;
    }

    /**
     * Helper method to convert a long value to byte array
     */
    private static byte[] longToBytes(long value) {
        return new byte[]{
                (byte) (value >>> 56),
                (byte) (value >>> 48),
                (byte) (value >>> 40),
                (byte) (value >>> 32),
                (byte) (value >>> 24),
                (byte) (value >>> 16),
                (byte) (value >>> 8),
                (byte) value
        };
    }
}